# Generated by Django 5.1.1 on 2024-10-01 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0008_alter_image_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_room',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='appname.room'),
        ),
    ]
