# Generated by Django 5.1.1 on 2024-10-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0011_remove_user_name_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='location',
            new_name='description',
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
